spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:xx:///localhost?stringtype=unspecified
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create

azure:
  storage:
    enabled: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    uk.gov.hmcts: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

thumbnail:
    imageThumbnailCreator: image/jpeg,image/png,image/gif,image/webp,image/bmp
    pdfThumbnailCreator: application/pdf


toggle:
    metadatamigration: false

dm:
  multipart:
    whitelist: "image/jpeg,application/pdf,image/tiff,image/png,image/bmp,text/plain,image/gif"
    whitelist-ext: ".jpg,.jpeg,.bmp,.tif,.tiff,.png,.pdf,.txt,.gif"
