package uk.gov.hmcts.dm.config.azure;

import com.azure.storage.blob.BlobContainerClient;
import com.azure.storage.blob.BlobContainerClientBuilder;
import com.azure.storage.blob.models.BlobStorageException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.net.InetAddress;
import java.net.UnknownHostException;

/**
 * This Azure container is used to access CSV files generated by the Case Document Access Management team in order
 * to update the meta data of documents in bulk.
 */
@Configuration
public class MetaDataAzureStorageConfiguration {

    @Value("${azure.storage.connection-string}")
    private String connectionString;

    @Value("${azure.storage.metadata-blob-container-reference}")
    private String metadataContainerName;

    @Value("${azure.storage.orphandocument-blob-container-reference}")
    private String orphanDocumentContainerName;

    private static final String AZURE_STORAGE_EMULATOR_AZURITE =  "azure-storage-emulator-azurite";

    @Bean(name = "metadata-storage")
    @ConditionalOnProperty(
        value = "toggle.metadatamigration",
        havingValue = "true")
    BlobContainerClient cloudBlobContainer() throws UnknownHostException {
        final String blobAddress = connectionString.contains(AZURE_STORAGE_EMULATOR_AZURITE)
            ? connectionString.replace(AZURE_STORAGE_EMULATOR_AZURITE,
                InetAddress.getByName(AZURE_STORAGE_EMULATOR_AZURITE).getHostAddress())
            : connectionString;

        final BlobContainerClient client = getClient(blobAddress, metadataContainerName);

        if (!client.exists()) {
            client.createIfNotExists();
        }
        return client;
    }

    BlobContainerClient getClient(String blobAddress, String containerName) {
        return new BlobContainerClientBuilder()
            .connectionString(blobAddress)
            .containerName(containerName)
            .buildClient();
    }

    @Bean(name = "orphandocument-storage")
    @ConditionalOnProperty(
        value = "toggle.orphandocumentdeletion",
        havingValue = "true")
    BlobContainerClient orphanFileCloudBlobContainer() throws UnknownHostException {
        final String blobAddress = connectionString.contains(AZURE_STORAGE_EMULATOR_AZURITE)
            ? connectionString.replace(AZURE_STORAGE_EMULATOR_AZURITE,
            InetAddress.getByName(AZURE_STORAGE_EMULATOR_AZURITE).getHostAddress())
            : connectionString;

        final BlobContainerClient client = getClient(blobAddress, orphanDocumentContainerName);

        if (!client.exists()) {
            client.createIfNotExists();
        }
        return client;
    }

}
