base-urls:
    idam-user: ${IDAM_API_URL:http://localhost:4501}
    idam-s2s: ${S2S_URL:http://localhost:4502}
    s2s-token: ${S2S_TOKEN:AAAAAAAAAAAAAAAA}
    dm-store: ${TEST_URL:http://localhost:4603}

toggle:
    metadatasearchendpoint: ${ENABLE_METADATA_SEARCH:true}
    documentandmetadatauploadendpoint: ${ENABLE_DOCUMENT_AND_METADATA_UPLOAD:true}
    folderendpoint: ${ENABLE_FOLDER_API:true}
    deleteenabled: ${ENABLE_DELETE:true}
    ttl: ${ENABLE_TTL:true}
    thumbnail: ${ENABLE_THUMBNAIL:true}
    includeidamhealth: ${ENABLE_IDAM_HEALTH_CHECK:false}


