DROP TABLE IF EXISTS
    BATCH_JOB_EXECUTION,
    BATCH_JOB_EXECUTION_CONTEXT,
    BATCH_JOB_EXECUTION_PARAMS,
    BATCH_JOB_INSTANCE,
    BATCH_MIGRATION_AUDIT_ENTRY,
    BATCH_STEP_EXECUTION,
    BATCH_STEP_EXECUTION_CONTEXT,
    SHEDLOCK;

DROP SEQUENCE IF EXISTS BATCH_STEP_EXECUTION_SEQ,
    BATCH_JOB_EXECUTION_SEQ,
    BATCH_JOB_SEQ;
